apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: token-secret
  namespace: default # Replace <namespace-name> with the actual namespace name
  annotations:
    kubernetes.io/service-account.name: "jenkins-deployer"
